load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load("@prelude//toolchains:csharp.bzl", "system_csharp_toolchain")

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_demo_toolchains()

system_csharp_toolchain(
    name = "csharp",
    framework_dirs = {
    },
    visibility = ["PUBLIC"],
)
